Update 1password cli installer to latest version

diff --git a/linux/setup/1password b/linux/setup/1password
--- a/linux/setup/1password
+++ b/linux/setup/1password
@@ -25,7 +25,9 @@ if have pacman; then
     fi
   }
 
-  url="https://cache.agilebits.com/dist/1P/op2/pkg/v2.7.0/op_linux_amd64_v2.7.0.zip"
+  arch=amd64
+  version=v2.31.1
+  url="https://cache.agilebits.com/dist/1P/op2/pkg/${version}/op_linux_${arch}_${version}.zip"
   clidir="$dir-cli"
   rm -rf "$clidir"
   mkdir "$clidir"
@@ -36,7 +38,9 @@ if have pacman; then
     && ensure-group \
     && sudo cp $clidir/op /usr/local/bin/ \
     && sudo chown root:"$group" /usr/local/bin/op \
-    && sudo chmod g+s /usr/local/bin/op)
+    && sudo chmod g+s /usr/local/bin/op \
+    && op --version \
+    || echo "Installation failed")
 
 else
   echo unknown os
